// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from ublox_ubx_msgs:msg/UBXEsfMeas.idl
// generated code does not contain a copyright notice

#ifndef UBLOX_UBX_MSGS__MSG__DETAIL__UBX_ESF_MEAS__STRUCT_H_
#define UBLOX_UBX_MSGS__MSG__DETAIL__UBX_ESF_MEAS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "std_msgs/msg/detail/header__struct.h"
// Member 'data'
#include "ublox_ubx_msgs/msg/detail/esf_meas_data_item__struct.h"

/// Struct defined in msg/UBXEsfMeas in the package ublox_ubx_msgs.
/**
  * this message contains a UBX-ESF-MEAS (0x10 0x02) record
  * External sesnor fusion measurement
 */
typedef struct ublox_ubx_msgs__msg__UBXEsfMeas
{
  /// Header timestamp should be acquisition time
  std_msgs__msg__Header header;
  /// time tag of measurement generated by external sensor
  uint32_t time_tag;
  /// time mark signal was supplied just prior to sending this message: 0 = None, 1 = on Ext0, 2 = on Ext1
  uint8_t time_mark_sent;
  /// trigger on rising (0) or falling (1) edge of time mark signal
  bool time_mark_edge;
  /// calibration time tag available. Always set to Zero
  bool calib_ttag_valid;
  /// Number of measurements contained in this message (optional, can be obtained from message size)
  uint8_t num_meas;
  /// identification number of data provideer
  uint16_t id;
  /// data array  of data_field & data_type
  ublox_ubx_msgs__msg__ESFMeasDataItem__Sequence data;
  /// receiver local time calibrated. This field must not be supplied when calb_ttag_valid is 0
  uint32_t calib_ttag;
} ublox_ubx_msgs__msg__UBXEsfMeas;

// Struct for a sequence of ublox_ubx_msgs__msg__UBXEsfMeas.
typedef struct ublox_ubx_msgs__msg__UBXEsfMeas__Sequence
{
  ublox_ubx_msgs__msg__UBXEsfMeas * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} ublox_ubx_msgs__msg__UBXEsfMeas__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // UBLOX_UBX_MSGS__MSG__DETAIL__UBX_ESF_MEAS__STRUCT_H_
