twist_mux:
  ros__parameters:
    output_topic: cmd_vel_out
    topic_timeout: 0.5
    default_timeout: 0.5
    topics:
      cmd_vel:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      cmd_vel_safe:
        topic: cmd_vel_safe
        timeout: 0.5
        priority: 100
    