controller_manager:
  ros__parameters:
<<<<<<< HEAD
    update_rate: 30
    # use_sim_time: true

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController
=======
    update_rate: 100.0
    use_sim_time: false  # This can be set to false if you're working with real hardware

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      publish_rate: 100.0 
      base_frame_id: base_link
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: "front_left_wheel_joint"
      right_wheel: "front_right_wheel_joint"
      wheel_separation: 0.530
      wheel_radius: 0.135
      cmd_vel_timeout: 0.25
>>>>>>> 983780703ae1681e6eebcb8c4634135f8974e252

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    steering_controller:
      type: position_controllers/JointGroupPositionController

diffbot_base_controller:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_footprint

    left_wheel_names: ["base_front_left_wheel_joint"]
    right_wheel_names: ["base_front_right_wheel_joint"]
    wheel_separation: 0.53
    wheel_radius: 0.260

    use_stamped_vel: false


    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters:

steering_controller:
  ros__parameters:
    joints:
      - liigend_to_kere_joint
    lower_limit: -0.7854
    upper_limit: 0.7854
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    pid:
      p: 1.0
      i: 0.0
      d: 0.0
