ekf_filter_node_odom:
  ros__parameters:

    frequency: 20.0

    frequency: 40.0

    two_d_mode: false
    print_diagnostics: true
    debug: false
    publish_tf: true
    use_sim_time: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom


    odom0: /odom
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   true,  true,  true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  false, false, true,  # Measure YAW only
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    mag0: /imu/mag
    mag0_config: [true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    mag0_queue_size: 10
    
    

ekf_filter_node_map:
  ros__parameters:

    frequency: 20.0

    frequency: 40.0

    two_d_mode: true
    print_diagnostics: true
    debug: false
    publish_tf: true
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map


    odom0: /odom
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   true,  true,  true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false


    odom1: /fix

    odom1: /gps/fix4

    odom1_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  false, false, true,  
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    mag0: /imu/mag
    mag0_config: [true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    mag0_queue_size: 10
    
navsat_transform_node:
  ros__parameters:
    use_sim_time: False
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: True
    broadcast_utm_transform: True
    broadcast_tf: True
    world_frame: 'map'
    base_link_frame: 'base_footprint'
    gps_frame: 'gps'
    odom_frame: 'odom'
    gps_topic: '/gps/fix'
    imu_topic: '/imu/data'
    use_odometry_source: False
    publish_filtered_gps: True
    wait_for_datum: True
    datum: "WGS84"
    debug: true

