ekf_filter_node_odom:
  ros__parameters:
    frequency: 40.0
    two_d_mode: false
    print_diagnostics: true
    debug: false
    publish_tf: true
    use_sim_time: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Enable position (x, y, z) and orientation (roll, pitch, yaw) from /odom
    odom0: /odom
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   true,  true,  true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  false, false, true,  # Measure YAW only
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    mag0: /imu/mag
    mag0_config: [true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    mag0_queue_size: 10

ekf_filter_node_map:
  ros__parameters:
    frequency: 40.0
    two_d_mode: true
    print_diagnostics: true
    debug: false
    publish_tf: true
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    # Enable position (x, y, z) and orientation (roll, pitch, yaw) from /odom
    odom0: /odom
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   true,  true,  true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    odom1: /gps/fix4
    odom1_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  false, false, true,  # Measure YAW only
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    mag0: /imu/mag
    mag0_config: [true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    mag0_queue_size: 10

