twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav # rviz goal
        timeout: 0.5
        priority: 10
      behavior:
        topic: cmd_vel_bt # behavior tree
        timeout: 0.5
        priority: 100
      joystick:
        topic: cmd_vel_joy # behavior tree
        timeout: 0.5
        priority: 100
